<?php
/**
 * Created by PhpStorm.
 * User: aymard.pro
 * Date: 15/04/2017
 * Time: 21:44
 */

namespace CakeSwagger\Controller;

use Laminas\Diactoros\Stream;
use function array_key_exists;
use Cake\Event\EventInterface;
use Cake\Routing\Router;
use CakeSwagger\Controller\AppController;
use function compact;
use OpenApi\Annotations\OpenApi;

class UiController extends AppController
{

  public function initialize(): void
  {
    parent::initialize(); // TODO: Change the autogenerated stub
    $this->loadComponent('RequestHandler');
  }

  /**
   * @param Event $event
   * @return \Cake\Http\Response|null|void
   * @throws \CakeSwagger\Exception\CakeSwaggerException
   */
  public function beforeFilter(EventInterface $event)
  {
    parent::beforeFilter($event);
    if ($this->getRequest()->getParam('action') === 'index') {
      $this->setRequest($this->getRequest()->withParam('_ext', null));
    }
  }

  /**
   * Index method
   *
   * @throws \Cake\Core\Exception\Exception
   */
  public function index()
  {
    $this->viewBuilder()->setLayout('CakeSwagger.default');
    $url = array_key_exists('directory', $this->config) && empty($this->config['directory']) ?
      'http://petstore.swagger.io/v2/swagger.json' :
      Router::url([
        'plugin' => 'CakeSwagger',
        'controller' => 'Ui',
        'action' => 'json'
      ], true);

    $this->set(compact('url'));
  }

  /**
   * Generate a swagger json
   *
   * @throws \CakeSwagger\Exception\CakeSwaggerException
   */
  public function json()
  {
    $response = $this->getResponse();
    $response = $response->withStringBody($this->_scan()->toJson());
    $response = $response->withType('application/json');
    return $response;
  }

  /**
   * Scan directories for build swagger documentation
   *
   * @return Swagger
   * @throws \CakeSwagger\Exception\CakeSwaggerException
   */
  private function _scan(): OpenApi
  {
    return \OpenApi\scan($this->config['directory'], $this->options);
  }

}
